### ISSUE TITLE
Question: Changes in STL

### ISSUE THREAD

**Issue by l4u** [ploopyco/nano-trackball#1]
What were the changes at https://github.com/ploopyco/nano-trackball/commit/ede7c89742cb379cdbf1e1d8379fff2fd7f83821 ?
I just printed an old version. Is there any major fix?
Thank you!

**Comment by ploopyco** [comment]
Yeah, rather large changes. The new version has an offset for the sensor relative to the ball, which makes the ball track better. The old version probably won't work.
